baseURL = ""
languageCode = "en-us"
title = "Ezhil"
theme = "ezhil"
paginate = 5
copyright = "© Copyright notice"
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = "UA-123-45"
disqusShortname = "ezhil-demo"
summaryLength = 20
themesDir = "themes"
publishDir = "public"

[params]
subtitle = "Clean and minimal personal [blog theme for Hugo](https://github.com/vividvilla/ezhil)"
disableDisqusTypes = [ "page" ]
featherIconsCDN = true
mode = "auto"

  [[params.social]]
  name = "Github"
  icon = "github"
  url = "https://github.com/vividvilla/ezhil"

  [[params.social]]
  name = "RSS"
  icon = "rss"
  url = "/index.xml"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[taxonomies]
tag = "tags"
